name: Fedora

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [28, 30, 33, 34]

    container: fedora:${{ matrix.tag }}

    steps:
      - run: dnf -y update && dnf -y install git xz
        if: ${{ matrix.tag != 'rawhide' }}

      - uses: actions/checkout@v3

      - run: ./test.sh
