name: publish

on:
  workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg: [aria2, axel, base16, base64, bash, bat, bison, bc, bsdtar, bzip2, b3sum, cargo-c, cmake, coreutils, cppcheck, ctop, curl, curlie, darkhttpd, dua, duf, dufs, dust, diffutils, difftastic, dog, dolt, dos2unix, dot_static, doxygen, d2, easyutils, ed, exa, fd, figlet, file, findutils, flex, flock, fzf, gawk, gettext-tools, gh, gindent, git, git-cliff, git-lfs, gitui, gitwatch, glib-tools, glow, gm4, gmake, gnupg, go-md2man, gogs, golang, golang@1.21, gotop, gotty, gperf, grep, grpc-plugins, gron, gsed, gtar, gzip, helm, hugo, incus, invoice, jj, jq, ko, lazygit, libxml2-utils, lolcat, lsd, lz4, lzip, mediainfo, mosh, mpg123, nap, nasm, ninja, nushell, openssl, patch, patchelf, pop, pigz, p7zip, pkg-config, pkgconf, pngquant, proot, putty, qpdf, qrencode, ripgrep, rsync, rtmpdump, silicon, sqlite3, starship, strace, svn-lite, swig, sysinfo, tcpdump, tealdeer, tig, tmux, tree, uctags, unrar, unzip, uppm, util-linux, volta, wget, xmake, xsltproc, xxd, xz, yasm, youtubedr, yq, zip, zopfli, zstd, zoxide]

    runs-on: ubuntu-latest

    container: alpine

    steps:
      - run: apk update
      - run: apk add curl g++ libc-dev linux-headers

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install ${{ matrix.pkg }} --link-type=static-full
      - run: ./ppkg pack    ${{ matrix.pkg }} -o . --exclude=include --exclude=lib

      - name: create ${{ matrix.pkg }}.yml
        run: |
          PACKAGE_SUMMARY="$(./ppkg info-installed ${{ matrix.pkg }} summary)"
          PACKAGE_WEB_URL="$(./ppkg info-installed ${{ matrix.pkg }} web-url)"
          PACKAGE_VERSION="$(./ppkg info-installed ${{ matrix.pkg }} version)"

          PACKAGE_BIN_SHA="$(sha256sum *.tar.xz | cut -d ' ' -f1)"

          PACKAGE_BIN_URL="https://github.com/leleliu008/uppm-package-repository-linux-x86_64/releases/download/@TAGNAME@/$(ls *.tar.xz)"

          cat > ${{ matrix.pkg }}.yml <<EOF
          summary: $PACKAGE_SUMMARY
          webpage: $PACKAGE_WEB_URL
          version: $PACKAGE_VERSION
          bin-url: $PACKAGE_BIN_URL
          bin-sha: $PACKAGE_BIN_SHA
          EOF

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ${{ matrix.pkg }}-*.tar.xz
            ${{ matrix.pkg }}.yml

  publish:
    needs: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls

      - run: |
          set -ex

          TAGNAME="$(date +%Y.%m.%d)"

          sed -i "s|@TAGNAME@|$TAGNAME|" *.yml

          mv *.yml formula/

          DIRNAME="uppm-formula-repository-linux-x86_64-$TAGNAME"

          install -d "$DIRNAME"

          cp -r formula "$DIRNAME/"

          tar cvJf "$DIRNAME.tar.xz" "$DIRNAME"

          sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [ppkg](https://github.com/leleliu008/ppkg).

          these packages are statically linked against [musl-libc](https://musl.libc.org/).

          these packages are relocatable which means that you can install them to anywhere.

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md

          git config --global user.name  "leleliu008"
          git config --global user.email "leleliu008@gmail.com"

          git pull

          git add formula
          git commit -m "release new version $TAGNAME"
          git push origin master
