name: VoidLinux-musl

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: voidlinux/voidlinux-musl

    steps:
      - run: xbps-install -Syu git xz

      - uses: actions/checkout@v3

      - run: ./test.sh
