name: VoidLinux-musl

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: voidlinux/voidlinux-musl

    steps:
      - run: xbps-install -Syu xbps
      - run: xbps-install -S
      - run: xbps-install -Syu git xz

      - run: git config --global --add safe.directory /__w/uppm-package-repository-linux-x86_64/uppm-package-repository-linux-x86_64
      - run: git init
      - run: git remote add origin https://github.com/${{github.repository}}
      - run: git config --local gc.auto 0
      - run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +${{github.sha}}:refs/remotes/origin/master
      - run: git checkout --progress --force -B master refs/remotes/origin/master

      - run: ls

      - run: ./test.sh
